<!doctype html>
<html lang="fr">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Boutique Mariage & Cérémonie</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
      <link href="css/style.css" rel="stylesheet">
      <link rel="stylesheet" href="css/styles.css">
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container-fluid">
            <!-- Logo à gauche -->
            <a class="navbar-brand" href="index.php">
            <img src="image/logo.png" alt="">
            </a>
            <!-- Toggler pour les petits écrans -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Menu de navigation -->
            <div class="collapse navbar-collapse" id="navbarNav">
               <!-- Liens centrés -->
               <ul class="navbar-nav mx-auto">
                  <li class="nav-item">
                     <a class="nav-link" href="index.php">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="article.php">Articles</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="collection.php">Collection</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="#">Discuter</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="#">À propos</a>
                  </li>
               </ul>
               <!-- Icône de recherche et compte utilisateur à droite -->
               <form class="d-flex ms-auto">
                  <input class="form-control me-2" type="search" placeholder="Rechercher...">
                  <button class="btn btn-outline-success" type="submit">
                  <img src="image/search.png" alt="">
                  </button>
               </form>
               <a class="btn btn-outline-primary ms-3" href="#">
               <img src="image/user.png" alt="">
               </a>
            </div>
         </div>
      </nav>